/*
  Warnings:

  - The values [QUIZ_9_PREPARING,QUIZ_9_ANSWERING,QUIZ_9_RESULTS,QUIZ_10_PREPARING,QUIZ_10_ANSWERING,QUIZ_10_RESULTS] on the enum `Phase` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "Phase_new" AS ENUM ('WAITING_FOR_PLAYERS', 'QUIZ_1_PREPARING', 'QUIZ_1_ANSWERING', 'QUIZ_1_RESULTS', 'QUIZ_2_PREPARING', 'QUIZ_2_ANSWERING', 'QUIZ_2_RESULTS', 'QUIZ_3_PREPARING', 'QUIZ_3_ANSWERING', 'QUIZ_3_RESULTS', 'QUIZ_4_PREPARING', 'QUIZ_4_ANSWERING', 'QUIZ_4_RESULTS', 'QUIZ_5_PREPARING', 'QUIZ_5_ANSWERING', 'QUIZ_5_RESULTS', 'QUIZ_6_PREPARING', 'QUIZ_6_ANSWERING', 'QUIZ_6_RESULTS', 'QUIZ_7_PREPARING', 'QUIZ_7_ANSWERING', 'QUIZ_7_RESULTS', 'QUIZ_8_PREPARING', 'QUIZ_8_ANSWERING', 'QUIZ_8_RESULTS', 'TERMO_PREPARING', 'TERMO_1_ANSWERING', 'TERMO_1_RESULTS', 'TERMO_2_ANSWERING', 'TERMO_2_RESULTS', 'TERMO_3_ANSWERING', 'TERMO_3_RESULTS', 'FINAL');
ALTER TABLE "Session" ALTER COLUMN "phase" DROP DEFAULT;
ALTER TABLE "Session" ALTER COLUMN "phase" TYPE "Phase_new" USING ("phase"::text::"Phase_new");
ALTER TYPE "Phase" RENAME TO "Phase_old";
ALTER TYPE "Phase_new" RENAME TO "Phase";
DROP TYPE "Phase_old";
ALTER TABLE "Session" ALTER COLUMN "phase" SET DEFAULT 'WAITING_FOR_PLAYERS';
COMMIT;
